#!/bin/bash
LETSENCRYPT_ENABLED="${LETSENCRYPT_ENABLED:=""}"
LETSENCRYPT_FORCE_NEW_CERT="${LETSENCRYPT_FORCE_NEW_CERT:=""}"
LETSENCRYPT_DOMAINS="${LETSENCRYPT_DOMAINS:=$(echo $LETSENCRYPT_DOMAINS | tr ',' '\n')}"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:=""}"
